theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
title: Ratisė
description: <em>Lietuviškos klaviatūros ergonomiškas išdėstymas.<br>Lithuanian Ergonomic Keyboard Layout.</em>
show_downloads: true
lang: lt_LT
encoding: UTF-8
