theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
title: Klaviatūros išdėstymas „Ratisė“
description: Lietuviškas ergonomiškas klaviatūros išdėstymas. Lithuanian Ergonomic Keyboard Layout.
lang: lt_LT
encoding: UTF-8
text_align:
  # Available values: start | end | left | right | center | justify | justify-all | match-parent
  desktop: justify
  mobile: justify
