theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
title: Klaviatūros išdėstymas „Ratisė“
description: Lietuviškas ergonomiškas klaviatūros išdėstymas.<br>Lithuanian Ergonomic Keyboard Layout.
show_downloads: true
lang: lt_LT
encoding: UTF-8
