theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
title: Klaviatūros išdėstymas „Ratisė“
description: <em>Lietuviškas ergonomiškas klaviatūros išdėstymas.<br>Lithuanian Ergonomic Keyboard Layout.</em>
show_downloads: true
lang: lt_LT
encoding: UTF-8
